export * from './obamaApp';
export * from './obamaParty';
export * from './bushApp';
export * from './bushParty';
export * from './clintonApp';
export * from './clintonParty';
export * from './trumpApp';
export * from './trumpParty';
export * from './defaults'
